### ISSUE TITLE
Exception - options.scrollYOffset is not a function

### ISSUE THREAD

**Issue by adambutler** [Redocly/redoc#1112]
With the latest release (`2.0.0-rc.18`) in all cases I am getting the following exception:

```
options.scrollYOffset is not a function 
  at StickyResponsiveSidebar.getScrollYOffset
```

**Comment by adambutler** [comment]
@RomanHotsiy I think this bug was introduced by https://github.com/Redocly/redoc/commit/21258a5

**Comment by RomanHotsiy** [comment]
I can't reproduce it locally. Could you provide a bit more details of how you use Redoc?

**Comment by RomanHotsiy** [comment]
Closing as stale

**Comment by RomanHotsiy** [comment]
Feel free to reopen if this is still the case
