### ISSUE TITLE
npx redoc-cli does not work with latest redoc (v2.0.0-rc45) version

### ISSUE THREAD

**Issue by koocbor** [Redocly/redoc#1440]
The redoc-cli stopped working when the latest version of redoc was pushed (v2.0.0.-rc45)

To reproduce:

1. Get petstore.yaml file from https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml
2. run `npx redoc-cli bundle ./petstore.yaml -o petstore.html`

An error from the Mobx package is thrown 
```
TypeError: Object(...) is not a function
    at new GroupModel (/Users/cook/.npm/_npx/87257/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:10182:49)
    at Function.MenuBuilder.getTagsItems (/Users/cook/.npm/_npx/87257/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:10348:24)
    at Function.MenuBuilder.buildStructure (/Users/cook/.npm/_npx/87257/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:10275:49)
    at new SpecStore (/Users/cook/.npm/_npx/87257/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:10161:53)
    at new AppStore (/Users/cook/.npm/_npx/87257/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:12804:21)
    at Module.<anonymous> (/Users/cook/.npm/_npx/87257/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:12788:43)
    at step (/Users/cook/.npm/_npx/87257/lib/node_modules/redoc-cli/node_modules/tslib/tslib.js:140:27)
    at Object.next (/Users/cook/.npm/_npx/87257/lib/node_modules/redoc-cli/node_modules/tslib/tslib.js:121:57)
    at fulfilled (/Users/cook/.npm/_npx/87257/lib/node_modules/redoc-cli/node_modules/tslib/tslib.js:111:62)
```

It looks like the latest version of redoc requires mobx@^6.0.1 but the redoc-cli package.json has `"mobx": "^4.2.0",`

**Comment by RomanHotsiy** [comment]
Should be fixed now with the latest redoc-cli@0.10.0.

**Comment by RomanHotsiy** [comment]
Thanks for reporting!

**Comment by koocbor** [comment]
Wow- thanks for the fast response 🎉
